#!/usr/bin/env bash
# =============================================================================
# 仓库卫生门禁（2026-09-10 行动）：拒绝垃圾/敏感文件被纳入版本库跟踪。
#
# 用法：
#   tools/check-repo-hygiene.sh            # 全量模式：检查所有已跟踪文件（CI 用）
#   tools/check-repo-hygiene.sh --staged   # 只检查本次 staged 的文件（pre-commit 用）
#
# 退出码：0 = 通过；1 = 存在违规。
# 规则来源：工作区 AGENTS.md「Temporary files policy」「AGENTS.md 不入库」等的可执行化。
# 误报处理：确属本仓合理文件 → 在本仓副本中调整规则/例外，并在提交说明中写明理由。
# =============================================================================
set -u

# 以脚本自身位置定位仓库根（CI 从 checkout 根运行、pre-commit 经绝对路径调用均可）
script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd) || { echo "✗ 无法定位脚本目录"; exit 1; }
root=$(git -C "$script_dir" rev-parse --show-toplevel 2>/dev/null) || { echo "✗ 不在 git 仓库内"; exit 1; }
cd "$root"

mode=all
[ "${1:-}" = "--staged" ] && mode=staged

if [ "$mode" = staged ]; then
    mapfile -d '' files < <(git diff --cached --name-only --diff-filter=ACMR -z)
else
    mapfile -d '' files < <(git ls-files -z)
fi
[ "${#files[@]}" -eq 0 ] && exit 0

fail=0
list=$(printf '%s\n' "${files[@]}")

# .env.example 是允许提交的模板，先从文件名检查里排除
name_list=$(printf '%s\n' "${files[@]}" | grep -v '\.env\.example$' || true)

# ---- 文件名拒绝规则：正则 :: 理由 -------------------------------------------
patterns=(
    '(^|/)tmp/'                  '临时产物目录（工作区规范：tmp/ 永不入库）'
    '(^|/)\.omo/'                'OpenCode/Boulder 状态目录'
    '(^|/)\.codegraph/'          'codegraph 索引'
    '(^|/)\.claude/'             'Claude Code 状态目录'
    '(^|/)\.mimocode/'           'mimocode 状态目录'
    '(^|/)\.zcode/'              'zcode 会话状态'
    '(^|/)\.idea/'               'IDE 配置'
    '(^|/)\.vscode/'             'IDE 配置'
    '(^|/)__pycache__/'          'Python 字节码缓存'
    '(^|/)\.venv/'               'Python 虚拟环境'
    '(^|/)node_modules/'         'npm 依赖'
    '(^|/)target/'               'Rust 构建产物'
    '(^|/)(build|dist|out)/'     '构建输出目录'
    'AGENTS\.md$'                'agent 上下文文件，各仓约定不入库'
    '\.DS_Store$'                'OS 垃圾文件'
    'Thumbs\.db$'                'OS 垃圾文件'
    '\.(swp|swo)$'               'vim 交换文件'
    '~$'                         '编辑器备份尾巴'
    '\.pyc$'                     'Python 字节码'
    '\.pcap(ng)?$'               '抓包文件（放 tmp/）'
    '\.(deb|pkg)$'               '离线软件包（放 tmp/）'
    '\.sqlite3?$'                '运行时数据库'
    '\.db(-shm|-wal)?$'          '运行时数据库（含 WAL 边车）'
    '\.log$'                     '日志文件'
    '\.prof(raw|data)$'          '性能分析产物'
    'coverage\.(out|html|txt)$'  '覆盖率产物'
    '\.onnx$'                    '模型文件按约定随部署分发，不入库'
    'cookies?\.txt$'             'curl cookie jar'
    'config\.local\.(toml|ya?ml|json)$' '本地配置覆盖，不入库'
    '\.env(\.[^.]+)?$'           '环境变量文件（.env.example 除外）'
    '(^|/)-[^/]+$'               '以 “-” 开头的文件名（curl 参数重定向事故类，如 -X）'
)

for ((i = 0; i < ${#patterns[@]}; i += 2)); do
    re=${patterns[i]}
    why=${patterns[i + 1]}
    while IFS= read -r f; do
        echo "✗ 违规文件: $f"
        echo "    规则: $re — $why"
        fail=1
    done < <(printf '%s\n' "$name_list" | grep -E "$re" || true)
done

# ---- 证书/私钥：只允许出现在测试夹具目录 ------------------------------------
while IFS= read -r f; do
    echo "✗ 违规文件: $f"
    echo "    规则: 证书/私钥 (.pem/.key/.p12/.pfx) 只允许位于 testdata/ 或 fixtures/ 下"
    fail=1
done < <(printf '%s\n' "$list" | grep -E '\.(pem|key|p12|pfx)$' | grep -Ev '(^|/)(testdata|fixtures)/' || true)

# ---- 内容标记：curl cookie jar ------------------------------------------------
# 标记用拼接构造，避免本脚本自身含完整字面量而自报。
cookie_marker='This file was generated by lib''curl'
if [ "$mode" = staged ]; then
    existing=()
    for f in "${files[@]}"; do [ -f "$f" ] && existing+=("$f"); done
    if [ "${#existing[@]}" -gt 0 ]; then
        while IFS= read -r f; do
            echo "✗ 违规文件: $f"
            echo "    规则: 内容含 libcurl cookie-jar 标记（会话凭证，严禁入库）"
            fail=1
        done < <(grep -Il "$cookie_marker" "${existing[@]}" 2>/dev/null || true)
    fi
else
    while IFS= read -r f; do
        echo "✗ 违规文件: $f"
        echo "    规则: 内容含 libcurl cookie-jar 标记（会话凭证，严禁入库）"
        fail=1
    done < <(git grep -Il "$cookie_marker" -- . || true)
fi

# ---- 大文件：单文件 > 10 MiB 拒绝 --------------------------------------------
if [ "$mode" = all ]; then
    while IFS= read -r -d '' f; do
        sz=$(stat -c%s "$f" 2>/dev/null) || continue
        if [ "$sz" -gt 10485760 ]; then
            echo "✗ 违规文件: $f（$((sz / 1048576)) MiB，超过 10 MiB 上限）"
            fail=1
        fi
    done < <(printf '%s\0' "${files[@]}")
fi

if [ "$fail" -ne 0 ]; then
    echo
    echo "✗ 仓库卫生门禁未通过（模式: $mode）。"
    echo "  处理：不该入库 → git rm --cached / 移入 tmp/；确属合理 → 调整本仓"
    echo "  tools/check-repo-hygiene.sh 规则并在提交说明中写明理由。"
    exit 1
fi
echo "✓ 仓库卫生门禁通过（模式: $mode，检查 ${#files[@]} 个文件）"
exit 0
